Don't assume python 2 is the default.
prettier/plugin-python pull request #48
Opened 2018-02-23 15:12 UTC by paradoxxxzero

Use explicit `python2` and `python3` executables.
`python2` link seems to be present on most arch.
Closes #47

2018-02-23 21:13 UTC, j-f1 approved these changes

2018-02-23 21:43 UTC, FuegoFro requested changes
Hm, a problem here is that `python2` is does not exist by default on macOS. Maybe we should have this try to look for `python2`, and if it doesn't exist fall back to `python`? Or we could determine if we're running on macOS and change which Python 2 executable we try to invoke in the first place? In any case, I'd be wary of breaking this on macOS or requiring extra steps to run it (like creating a `python2` symlink).

2018-02-24 14:02 UTC, paradoxxxzero commented
Indeed, but we should also check that python is really the python 2 version
otherwise we could get some obscure bugs. Another solution could be
supporting both python version formatting with both python version parsing,
if that's even possible. (The #47 was making all the python 2 tests pass
with python 3 parsing.)

Le ven. 23 févr. 2018 à 22:43, Danny Weinberg <notifications@github.com> a
écrit :

> *@FuegoFro* requested changes on this pull request.
>
> Hm, a problem here is that python2 is does not exist by default on macOS.
> Maybe we should have this try to look for python2, and if it doesn't
> exist fall back to python? Or we could determine if we're running on
> macOS and change which Python 2 executable we try to invoke in the first
> place? In any case, I'd be wary of breaking this on macOS or requiring
> extra steps to run it (like creating a python2 symlink).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/prettier/plugin-python/pull/48#pullrequestreview-99061824>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAQjKDUn2brVsby4mIIbpLLy-F3wI9d4ks5tXzEBgaJpZM4SRBMO>
> .
>

2018-05-12 09:39 UTC, lipis commented
What's the status with this one?

2018-05-15 15:14 UTC, FuegoFro commented
I think if we just change the string for python2 from `""` to `"2.7"` that will likely fix this and work everywhere. Thoughts on that?

2019-03-08 01:44 UTC, FuegoFro commented
It's been over a year since this has had meaningful activity and this project is deprecated, so I'm going to close this out. If folks do want this change we can re-open it 🙂

2019-03-08 01:44 UTC, closed without merging